#!/usr/bin/env python3
"""Tune the ancestry support threshold directly from prepared cal-support NPZs.

This avoids an unnecessary manual CSV step.  ``--truth-plan`` is the role-
disjoint calibration plan generated by ``generate_calibration_plan.py``.
Only cal-support descendants may be used here; test descendants are rejected by
ID unless ``--unsafe`` is explicitly set for debugging.
"""
from __future__ import annotations
import argparse,csv,glob,json,sys
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'code'))
from fas_core.decompose import fas_decompose


def parent_f1(true,pred):
    t=set(true); p=set(pred); tp=len(t&p)
    pr=tp/len(p) if p else (1.0 if not t else 0.0)
    re=tp/len(t) if t else 1.0
    return 2*pr*re/(pr+re) if pr+re else 0.0


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('inputs',nargs='+')
    ap.add_argument('--truth-plan',required=True)
    ap.add_argument('--grid',default='0.001,0.002,0.005,0.01,0.02,0.05,0.1,0.15,0.2')
    ap.add_argument('--output',default='runs/calibration/scores/support_threshold.json')
    ap.add_argument('--predictions-output',default='runs/calibration/scores/support_predictions.csv')
    ap.add_argument('--unsafe',action='store_true')
    args=ap.parse_args()
    truth={}
    for r in csv.DictReader(open(args.truth_plan,encoding='utf-8',newline='')):
        truth[r['calibration_id']]=list(json.loads(r['parents']))
    files=[]
    for pat in args.inputs:
        m=glob.glob(pat); files.extend(m if m else [pat])
    rows=[]
    for x in sorted(set(files)):
        p=Path(x); cid=p.stem
        if cid not in truth:
            if args.unsafe: continue
            raise SystemExit(f'{cid}: not found in cal-support truth plan')
        z=np.load(p,allow_pickle=False); A=np.asarray(z['A'],float); y=np.asarray(z['y'],float)
        weights=np.asarray(z['weights'],float) if 'weights' in z else None
        dec=fas_decompose(A,y,weights=weights)
        names=[str(v) for v in (z['ancestor_names'].tolist() if 'ancestor_names' in z else [f'ancestor_{i}' for i in range(A.shape[1])])]
        rows.append({'calibration_id':cid,'parent_names':names,'pi':np.asarray(dec['pi'],float),'true_support':truth[cid]})
    if not rows: raise SystemExit('no cal-support prepared NPZs found')
    grid=[float(x) for x in args.grid.split(',') if x.strip()]
    scores=[]
    for th in grid:
        vals=[]
        for r in rows:
            pred=[n for n,v in zip(r['parent_names'],r['pi']) if v>th]
            vals.append(parent_f1(r['true_support'],pred))
        scores.append({'threshold':th,'mean_parent_f1':float(np.mean(vals)),'std_parent_f1':float(np.std(vals,ddof=1)) if len(vals)>1 else 0.0})
    best=max(scores,key=lambda z:(z['mean_parent_f1'],z['threshold']))
    out=Path(args.output); out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text(json.dumps({'selected':best,'grid':scores,'n_validation':len(rows),'source_role':'cal_support'},indent=2),encoding='utf-8')
    po=Path(args.predictions_output); po.parent.mkdir(parents=True,exist_ok=True)
    with po.open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=['calibration_id','parent_names','true_support','pred_pi'])
        w.writeheader()
        for r in rows:
            w.writerow({'calibration_id':r['calibration_id'],'parent_names':';'.join(r['parent_names']),'true_support':';'.join(r['true_support']),'pred_pi':';'.join(f'{v:.10g}' for v in r['pi'])})
    print(json.dumps({'selected':best,'n_validation':len(rows),'output':str(out)},indent=2))

if __name__=='__main__': main()
